import { registerBundle } from "../shared/i18nB";

registerBundle(
  "onboarding",
  {
    title: "Crear cuenta y configurar",
    stepOf: "Paso {{current}} de {{total}}",
    steps: {
      account: "Crear cuenta",
      basics: "Datos básicos",
      parq: "Cuestionario de salud (PAR-Q)",
      equipment: "Equipamiento y preferencias",
    },
    account: {
      heading: "Crear tu cuenta",
      email: "Correo electrónico",
      password: "Contraseña",
      passwordHint: "Mínimo 10 caracteres. Recomendado: frase larga con números",
      displayName: "Nombre para mostrar",
      errorEmail: "Introduce un correo válido.",
      errorPasswordShort: "La contraseña debe tener al menos 10 caracteres.",
      errorName: "Indica un nombre.",
      errorConflict: "Ya existe una cuenta con ese correo.",
      errorForbidden: "El registro está cerrado en este servidor",
      errorCsrf: "Error de seguridad (CSRF). Por favor, recarga la página e intenta de nuevo.",
      errorGeneric: "No se ha podido crear la cuenta. Por favor, intenta de nuevo.",
    },
    basics: {
      heading: "Tus datos básicos",
      sex: "Sexo",
      sexHint: "Solo se usa para personalizar el plan (ejercicios y cargas esperadas). Puedes cambiarlo en cualquier momento.",
      birthDate: "Fecha de nacimiento",
      errorBirthDate: "Introduce una fecha de nacimiento válida.",
      height: "Altura (cm)",
      errorHeight: "La altura debe estar entre 100 y 250 cm.",
      weight: "Peso (kg)",
      errorWeight: "El peso debe estar entre 20 y 400 kg.",
      experience: "Experiencia en entrenamiento",
    },
    parq: {
      heading: "Cuestionario de aptitud (PAR-Q)",
      intro: "Responde estos 7 preguntas sobre tu salud. Si respondes «sí» a alguna, tu plan comenzará en nivel principiante (recomendado por precaución).",
      questions: {
        heart_condition: "¿Te ha diagnosticado un médico una enfermedad del corazón?",
        chest_pain_activity: "¿Sientes dolor en el pecho durante la actividad física?",
        chest_pain_rest: "¿Has sentido dolor en el pecho en los últimos 3 meses, en reposo?",
        dizziness_or_fainting: "¿Has perdido el conocimiento o te has caído por mareo?",
        bone_or_joint_problem: "¿Tienes un problema óseo o articular que te limite?",
        blood_pressure_or_heart_medication: "¿Tomas medicinas para la presión arterial o el corazón?",
        other_reason: "¿Hay algún motivo por el que no deberías entrenar?",
      },
      yes: "Sí",
      no: "No",
      flagged: "Has respondido «sí» a una o más preguntas. Por tu seguridad, ajustaremos tu nivel a principiante. Puedes aumentarlo más adelante.",
      disclaimer: "Consulta con un profesional sanitario antes de empezar.",
    },
    equipment: {
      heading: "Equipamiento y preferencias",
      preset: "Equipamiento disponible",
      items: "Selecciona los equipos con los que cuentas",
      itemsRequired: "Marca al menos un tipo de equipamiento.",
      avoidMuscles: "Músculos a evitar (p. ej., lesiones)",
      dietToggle: "Activar el módulo de nutrición",
      dietHint: "Registra comidas y macros. Puedes desactivarlo después en tu perfil.",
    },
    done: {
      heading: "Todo listo",
      body: "Tu cuenta está lista. Ahora puedes crear tu primer plan personalizado.",
      recommendation: "Recomendación del médico",
      cta: "Crear mi rutina",
    },
    actions: {
      back: "Atrás",
      next: "Continuar",
      finish: "Terminar",
      saving: "Guardando…",
    },
    errorSave: "No se ha podido guardar tu perfil. Inténtalo de nuevo.",
  },
  {
    title: "Create account and set up",
    stepOf: "Step {{current}} of {{total}}",
    steps: {
      account: "Create account",
      basics: "Basic info",
      parq: "Health questionnaire (PAR-Q)",
      equipment: "Equipment and preferences",
    },
    account: {
      heading: "Create your account",
      email: "Email",
      password: "Password (min. 10 characters)",
      passwordHint: "Recommended: long phrase with numbers",
      displayName: "Display name",
      errorEmail: "Invalid email",
      errorPasswordShort: "Password must be at least 10 characters",
      errorName: "Name cannot be empty",
      errorConflict: "This email is already registered",
      errorForbidden: "Registration is closed on this server",
      errorCsrf: "Security error (CSRF). Please reload the page and try again.",
      errorGeneric: "Could not create account. Please try again.",
    },
    basics: {
      heading: "Your basic info",
      sex: "Sex",
      sexHint: "Only used to personalize your plan (exercises and expected loads). You can change it anytime.",
      birthDate: "Date of birth",
      errorBirthDate: "Invalid or future date of birth",
      height: "Height (cm)",
      errorHeight: "Height must be between 100 and 250 cm",
      weight: "Weight (kg, optional)",
      errorWeight: "Weight must be between 20 and 400 kg",
      experience: "Training experience",
    },
    parq: {
      heading: "Physical Activity Readiness Questionnaire (PAR-Q)",
      intro: "Answer these 7 questions about your health. If you answer «yes» to any, your plan will start at beginner level (recommended as a precaution).",
      questions: {
        heart_condition: "Has a doctor ever diagnosed you with a heart condition?",
        chest_pain_activity: "Do you feel chest pain during physical activity?",
        chest_pain_rest: "Have you felt chest pain in the last 3 months at rest?",
        dizziness_or_fainting: "Have you ever lost consciousness or fallen due to dizziness?",
        bone_or_joint_problem: "Do you have a bone or joint problem that limits you?",
        blood_pressure_or_heart_medication: "Do you take medicine for blood pressure or the heart?",
        other_reason: "Is there any reason you should not exercise?",
      },
      yes: "Yes",
      no: "No",
      flagged: "You answered «yes» to one or more questions. Your plan will start at beginner level as a precaution. You can increase the level when you feel ready.",
      disclaimer: "If you're unsure about any answer, consult your doctor before starting to exercise.",
    },
    equipment: {
      heading: "Equipment and preferences",
      preset: "Available equipment",
      items: "Select your available equipment",
      itemsRequired: "You must select at least one custom equipment",
      avoidMuscles: "Muscles to avoid (e.g., injuries)",
      dietToggle: "Enable nutrition module",
      dietHint: "Log meals and macros. You can disable it later in your profile.",
    },
    done: {
      heading: "Welcome to Forja!",
      body: "Your account is ready. Next, you'll create your first personalized program.",
      recommendation: "Recommendation",
      cta: "Create my first program",
    },
    actions: {
      back: "Back",
      next: "Continue",
      finish: "Finish",
      saving: "Saving…",
    },
    errorSave: "Could not save your profile. Please try again.",
  },
);
