import { registerBundle } from "../shared/i18nB";

/** Cadenas del reproductor, el resumen y la pantalla «Hoy» (es/en). */
registerBundle(
  "session",
  {
    title: "Sesión",
    loading: "Cargando la sesión…",
    empty: "No hay ninguna sesión en curso.",
    backToToday: "Volver a Hoy",
    exerciseOf: "Ejercicio {{current}} de {{total}}",
    setOf: "Serie {{current}} de {{total}}",
    target: "Objetivo",
    reps: "repeticiones",
    repsRange: "{{min}}–{{max}} rep.",
    rirTarget: "RIR {{rir}}",
    suggested: "Peso sugerido",
    lastTime: "La última vez",
    lastSet: "{{weight}} kg × {{reps}}",
    weight: "Peso (kg)",
    repsField: "Repeticiones",
    rir: "Repeticiones en reserva (RIR)",
    keypadFor: "Teclado numérico para {{field}}",
    key: "Tecla {{key}}",
    backspace: "Borrar",
    decimal: "Coma decimal",
    done: "Serie hecha",
    undo: "Deshacer última serie",
    warmup: "Calentamiento de aproximación",
    warmupSet: "{{weight}} kg × {{reps}} ({{percent}} %)",
    warmupDone: "Hecha",
    plates: "Discos por lado: {{plates}} kg",
    noPlates: "Solo barra",
    platesTitle: "Calculadora de discos",
    instructions: "Instrucciones paso a paso",
    hideInstructions: "Ocultar instrucciones",
    swap: "Cambiar ejercicio",
    swapTitle: "Alternativas para este ejercicio",
    swapNone: "No hay alternativas disponibles.",
    swapUse: "Usar {{name}}",
    rest: "Descanso",
    restRemaining: "Quedan {{seconds}} s de descanso",
    restOver: "¡Descanso terminado!",
    restOverBody: "Toca para seguir con la siguiente serie.",
    restMinus: "Restar 15 segundos",
    restPlus: "Sumar 15 segundos",
    restSkip: "Saltar descanso",
    next: "Siguiente",
    finishNow: "Terminar sesión",
    effortTitle: "¿Qué esfuerzo has sentido?",
    effortLabel: "Esfuerzo percibido",
    effortHelp: "De 1 (muy fácil) a 10 (máximo esfuerzo).",
    effort: "Esfuerzo {{value}}",
    saveFinish: "Guardar y ver resumen",
    pendingSync: "{{count}} cambios pendientes de sincronizar",
    rejected: "El servidor no aceptó «{{title}}».",
    offline: "Sin conexión: tus series se guardan en el dispositivo y se enviarán al volver la red.",
    notes: "Notas del ejercicio",
    summaryTitle: "Resumen de la sesión",
    // Partido en 3 para el acento de titular (F5, técnica 5): concatenados dan exactamente
    // "Resumen de la sesión" (igual que `summaryTitle`, mantener en sincronía si cambia).
    summaryTitleLead: "Resumen de la ",
    summaryTitleAccent: "sesión",
    summaryTitleTrail: "",
    summaryLoading: "Calculando el resumen…",
    duration: "Duración",
    volume: "Volumen",
    sets: "Series",
    totalReps: "Repeticiones",
    exercises: "Ejercicios",
    records: "Récords",
    recordNone: "Sin récords nuevos esta vez. La constancia también cuenta.",
    recordKind_e1rm: "1RM estimado",
    recordKind_heaviest_set: "Serie más pesada",
    recordKind_volume: "Volumen",
    localSummary: "Resumen calculado en este dispositivo; los récords aparecerán al sincronizar.",
    minutes: "{{count}} min",
    startingError: "No se ha podido iniciar la sesión.",
  },
  {
    title: "Session",
    loading: "Loading the session…",
    empty: "There is no session in progress.",
    backToToday: "Back to Today",
    exerciseOf: "Exercise {{current}} of {{total}}",
    setOf: "Set {{current}} of {{total}}",
    target: "Target",
    reps: "reps",
    repsRange: "{{min}}–{{max}} reps",
    rirTarget: "RIR {{rir}}",
    suggested: "Suggested weight",
    lastTime: "Last time",
    lastSet: "{{weight}} kg × {{reps}}",
    weight: "Weight (kg)",
    repsField: "Reps",
    rir: "Reps in reserve (RIR)",
    keypadFor: "Numeric keypad for {{field}}",
    key: "Key {{key}}",
    backspace: "Delete",
    decimal: "Decimal point",
    done: "Set done",
    undo: "Undo last set",
    warmup: "Warm-up ramp",
    warmupSet: "{{weight}} kg × {{reps}} ({{percent}}%)",
    warmupDone: "Done",
    plates: "Plates per side: {{plates}} kg",
    noPlates: "Bar only",
    platesTitle: "Plate calculator",
    instructions: "Step-by-step instructions",
    hideInstructions: "Hide instructions",
    swap: "Swap exercise",
    swapTitle: "Alternatives for this exercise",
    swapNone: "No alternatives available.",
    swapUse: "Use {{name}}",
    rest: "Rest",
    restRemaining: "{{seconds}} s of rest left",
    restOver: "Rest is over!",
    restOverBody: "Tap to continue with the next set.",
    restMinus: "Subtract 15 seconds",
    restPlus: "Add 15 seconds",
    restSkip: "Skip rest",
    next: "Next",
    finishNow: "Finish session",
    effortTitle: "How hard did it feel?",
    effortLabel: "Perceived effort",
    effortHelp: "From 1 (very easy) to 10 (maximum effort).",
    effort: "Effort {{value}}",
    saveFinish: "Save and view summary",
    pendingSync: "{{count}} changes waiting to sync",
    rejected: "The server did not accept “{{title}}”.",
    offline: "Offline: your sets are saved on this device and will be sent when the network returns.",
    notes: "Exercise notes",
    summaryTitle: "Session summary",
    summaryTitleLead: "",
    summaryTitleAccent: "Session",
    summaryTitleTrail: " summary",
    summaryLoading: "Calculating the summary…",
    duration: "Duration",
    volume: "Volume",
    sets: "Sets",
    totalReps: "Reps",
    exercises: "Exercises",
    records: "Records",
    recordNone: "No new records this time. Consistency counts too.",
    recordKind_e1rm: "Estimated 1RM",
    recordKind_heaviest_set: "Heaviest set",
    recordKind_volume: "Volume",
    localSummary: "Summary calculated on this device; records will appear after syncing.",
    minutes: "{{count}} min",
    startingError: "The session could not be started.",
  },
);

registerBundle(
  "todayB",
  {
    scheduledFor: "Toca hoy: {{name}}",
    minutes: "≈ {{count}} min",
    start: "Empezar",
    starting: "Preparando…",
    resume: "Continuar sesión en curso",
    restDay: "Hoy es día de descanso. Recuperar también es entrenar.",
    noProgram: "Aún no tienes un programa activo.",
    createProgram: "Crear una rutina",
    programCompleted: "Has completado tu programa. ¡Buen trabajo!",
    weekSummary: "Resumen de la semana",
    lastRecord: "Último récord",
    recordValue: "{{name}}: {{value}} kg",
    noRecord: "Todavía sin récords.",
    bodyWeight: "Peso corporal",
    bodyWeightLatest: "Último: {{weight}} kg",
    bodyWeightAverage: "Media de 7 días: {{weight}} kg",
    bodyWeightInput: "Peso de hoy (kg)",
    bodyWeightSave: "Guardar peso",
    bodyWeightSaved: "Peso guardado.",
    bodyWeightError: "No se ha podido guardar el peso.",
    nutrition: "Ir a Nutrición",
    pendingSync: "Cambios pendientes de sincronizar: {{count}}",
  },
  {
    scheduledFor: "Today: {{name}}",
    minutes: "≈ {{count}} min",
    start: "Start",
    starting: "Getting ready…",
    resume: "Resume the session in progress",
    restDay: "Today is a rest day. Recovering is training too.",
    noProgram: "You do not have an active program yet.",
    createProgram: "Create a routine",
    programCompleted: "You have completed your program. Great work!",
    weekSummary: "This week",
    lastRecord: "Latest record",
    recordValue: "{{name}}: {{value}} kg",
    noRecord: "No records yet.",
    bodyWeight: "Body weight",
    bodyWeightLatest: "Latest: {{weight}} kg",
    bodyWeightAverage: "7-day average: {{weight}} kg",
    bodyWeightInput: "Today's weight (kg)",
    bodyWeightSave: "Save weight",
    bodyWeightSaved: "Weight saved.",
    bodyWeightError: "The weight could not be saved.",
    nutrition: "Go to Nutrition",
    pendingSync: "Changes waiting to sync: {{count}}",
  },
);
