import { registerBundle } from "../shared/i18nB";

registerBundle(
  "nutrition",
  {
    title: "Nutrición",
    loading: "Cargando tu nutrición…",
    error: "No se ha podido cargar la nutrición.",
    unavailable: "La función de nutrición no está disponible en este servidor.",
    disabled: "La nutrición está desactivada. Puedes activarla cuando quieras.",
    enable: "Activar nutrición",
    safetyTitle: "Aviso de seguridad",
    safetyBody:
      "Estas cifras son orientativas y no sustituyen el consejo de un dietista-nutricionista o de tu profesional sanitario.",
    targetTitle: "Objetivo diario",
    kcal: "kcal",
    protein: "Proteína",
    fat: "Grasa",
    carbs: "Hidratos",
    fiber: "Fibra",
    grams: "{{value}} g",
    ringLabel: "{{name}}: {{value}}",
    ringShare: "{{percent}} % de las calorías",
    blockedTitle: "No calculamos un objetivo en tu caso",
    noTarget: "Aún no hay un objetivo calculado.",
    recalc: "Recalcular objetivo",
    settingsTitle: "Ajustes",
    goal: "Objetivo",
    pace: "Ritmo",
    dietType: "Tipo de dieta",
    mealsPerDay: "Comidas al día",
    allergens: "Alergias e intolerancias",
    pregnant: "Estoy embarazada",
    breastfeeding: "Estoy en periodo de lactancia",
    saveSettings: "Guardar ajustes",
    saved: "Ajustes guardados.",
    goal_lose: "Perder grasa",
    goal_maintain: "Mantener",
    goal_gain: "Ganar músculo",
    goal_recomp: "Recomposición",
    pace_gentle: "Suave",
    pace_standard: "Estándar",
    diet_omnivore: "Omnívora",
    diet_pescatarian: "Pescetariana",
    diet_vegetarian: "Vegetariana",
    diet_vegan: "Vegana",
    allergen_gluten: "Gluten",
    allergen_lactose: "Lactosa",
    allergen_tree_nuts: "Frutos secos",
    allergen_egg: "Huevo",
    allergen_fish: "Pescado",
    allergen_shellfish: "Marisco",
    allergen_soy: "Soja",
    allergen_peanuts: "Cacahuete",
    planTitle: "Plan semanal",
    generate: "Generar plan de esta semana",
    generating: "Generando…",
    noPlan: "Todavía no tienes un plan para esta semana.",
    day: "Día {{n}}",
    dayTotals: "Total del día: {{kcal}} kcal · P {{protein}} g · G {{fat}} g · H {{carbs}} g",
    deviation: "Diferencia con el objetivo: {{kcal}} kcal",
    slot_breakfast: "Desayuno",
    slot_mid_morning: "Media mañana",
    slot_lunch: "Comida",
    slot_snack: "Merienda",
    slot_dinner: "Cena",
    item: "{{name}} · {{grams}} g · {{kcal}} kcal",
    swap: "Cambiar {{name}}",
    swapTitle: "Cambiar alimento",
    swapAuto: "Elegir automáticamente",
    swapSearch: "Buscar un alimento",
    swapUse: "Usar {{name}}",
    swapCancel: "Cancelar",
    swapError: "No se ha podido cambiar el alimento.",
    shoppingTitle: "Lista de la compra",
    shoppingItem: "{{name}} — {{grams}} g",
    shoppingChecked: "Marcar {{name}} como comprado",
    shoppingEmpty: "La lista está vacía.",
    notices: "Notas sobre tu plan",
    notice_tolerance_not_met:
      "Por ajustes de alimentos, algún día se acerca al objetivo con una pequeña diferencia. Es informativo: no hace falta corregir nada.",
    generateError: "No se ha podido generar el plan.",
    settingsError: "No se han podido guardar los ajustes.",
  },
  {
    title: "Nutrition",
    loading: "Loading your nutrition…",
    error: "Nutrition could not be loaded.",
    unavailable: "The nutrition feature is not available on this server.",
    disabled: "Nutrition is turned off. You can turn it on whenever you like.",
    enable: "Turn on nutrition",
    safetyTitle: "Safety notice",
    safetyBody:
      "These figures are approximate and do not replace the advice of a registered dietitian or your healthcare professional.",
    targetTitle: "Daily target",
    kcal: "kcal",
    protein: "Protein",
    fat: "Fat",
    carbs: "Carbs",
    fiber: "Fiber",
    grams: "{{value}} g",
    ringLabel: "{{name}}: {{value}}",
    ringShare: "{{percent}}% of calories",
    blockedTitle: "We do not calculate a target in your case",
    noTarget: "No target has been calculated yet.",
    recalc: "Recalculate target",
    settingsTitle: "Settings",
    goal: "Goal",
    pace: "Pace",
    dietType: "Diet type",
    mealsPerDay: "Meals per day",
    allergens: "Allergies and intolerances",
    pregnant: "I am pregnant",
    breastfeeding: "I am breastfeeding",
    saveSettings: "Save settings",
    saved: "Settings saved.",
    goal_lose: "Lose fat",
    goal_maintain: "Maintain",
    goal_gain: "Gain muscle",
    goal_recomp: "Recomposition",
    pace_gentle: "Gentle",
    pace_standard: "Standard",
    diet_omnivore: "Omnivore",
    diet_pescatarian: "Pescatarian",
    diet_vegetarian: "Vegetarian",
    diet_vegan: "Vegan",
    allergen_gluten: "Gluten",
    allergen_lactose: "Lactose",
    allergen_tree_nuts: "Tree nuts",
    allergen_egg: "Egg",
    allergen_fish: "Fish",
    allergen_shellfish: "Shellfish",
    allergen_soy: "Soy",
    allergen_peanuts: "Peanuts",
    planTitle: "Weekly plan",
    generate: "Generate this week's plan",
    generating: "Generating…",
    noPlan: "You do not have a plan for this week yet.",
    day: "Day {{n}}",
    dayTotals: "Day total: {{kcal}} kcal · P {{protein}} g · F {{fat}} g · C {{carbs}} g",
    deviation: "Difference from target: {{kcal}} kcal",
    slot_breakfast: "Breakfast",
    slot_mid_morning: "Mid-morning",
    slot_lunch: "Lunch",
    slot_snack: "Snack",
    slot_dinner: "Dinner",
    item: "{{name}} · {{grams}} g · {{kcal}} kcal",
    swap: "Swap {{name}}",
    swapTitle: "Swap food",
    swapAuto: "Pick automatically",
    swapSearch: "Search for a food",
    swapUse: "Use {{name}}",
    swapCancel: "Cancel",
    swapError: "The food could not be swapped.",
    shoppingTitle: "Shopping list",
    shoppingItem: "{{name}} — {{grams}} g",
    shoppingChecked: "Mark {{name}} as bought",
    shoppingEmpty: "The list is empty.",
    notices: "Notes about your plan",
    notice_tolerance_not_met:
      "Because of food adjustments, some day lands close to the target with a small difference. This is informational: nothing needs fixing.",
    generateError: "The plan could not be generated.",
    settingsError: "The settings could not be saved.",
  },
);
