import { registerBundle } from "../shared/i18nB";

registerBundle(
  "admin",
  {
    title: "Administración",
    forbidden: "Solo las personas administradoras pueden ver esta sección.",
    loading: "Cargando…",
    error: "No se ha podido cargar.",
    settings: "Ajustes globales",
    registrationOpen: "Registro abierto a nuevas cuentas",
    dietFeature: "Función de nutrición disponible",
    mediaAuth: "Medios solo para usuarios autenticados: {{value}}",
    yes: "sí",
    no: "no",
    datasetCommit: "Commit del dataset",
    saved: "Guardado.",
    saveError: "No se ha podido guardar.",
    users: "Usuarios",
    search: "Buscar por email o nombre",
    email: "Email",
    name: "Nombre",
    role: "Rol",
    active: "Activo",
    lastLogin: "Último acceso",
    never: "Nunca",
    role_user: "Usuario",
    role_admin: "Administrador",
    roleOf: "Rol de {{email}}",
    activeOf: "Cuenta activa de {{email}}",
    ingest: "Ingesta del catálogo",
    ingestHelp: "Una simulación (dry-run) muestra el diff sin modificar el catálogo.",
    ingestDry: "Simular ingesta",
    ingestReal: "Lanzar ingesta",
    ingestStarted: "Ingesta en cola.",
    runs: "Ejecuciones recientes",
    noRuns: "Todavía no hay ejecuciones.",
    runTitle: "{{status}} · {{commit}}",
    dryRun: "simulación",
    status_queued: "En cola",
    status_running: "En curso",
    status_succeeded: "Correcta",
    status_failed: "Con errores",
    counts: "{{added}} nuevos · {{updated}} actualizados · {{deprecated}} retirados · {{unchanged}} sin cambios",
    diff: "Diff: {{added}} añadidos, {{updated}} actualizados, {{deprecated}} retirados",
    errors: "Errores",
    warnings: "Avisos",
    started: "Inicio: {{date}}",
  },
  {
    title: "Administration",
    forbidden: "Only administrators can see this section.",
    loading: "Loading…",
    error: "Could not load.",
    settings: "Global settings",
    registrationOpen: "Registration open to new accounts",
    dietFeature: "Nutrition feature available",
    mediaAuth: "Media only for signed-in users: {{value}}",
    yes: "yes",
    no: "no",
    datasetCommit: "Dataset commit",
    saved: "Saved.",
    saveError: "Could not save.",
    users: "Users",
    search: "Search by email or name",
    email: "Email",
    name: "Name",
    role: "Role",
    active: "Active",
    lastLogin: "Last login",
    never: "Never",
    role_user: "User",
    role_admin: "Administrator",
    roleOf: "Role of {{email}}",
    activeOf: "Account active for {{email}}",
    ingest: "Catalog ingest",
    ingestHelp: "A dry run shows the diff without changing the catalog.",
    ingestDry: "Dry run",
    ingestReal: "Start ingest",
    ingestStarted: "Ingest queued.",
    runs: "Recent runs",
    noRuns: "There are no runs yet.",
    runTitle: "{{status}} · {{commit}}",
    dryRun: "dry run",
    status_queued: "Queued",
    status_running: "Running",
    status_succeeded: "Succeeded",
    status_failed: "Failed",
    counts: "{{added}} new · {{updated}} updated · {{deprecated}} deprecated · {{unchanged}} unchanged",
    diff: "Diff: {{added}} added, {{updated}} updated, {{deprecated}} deprecated",
    errors: "Errors",
    warnings: "Warnings",
    started: "Started: {{date}}",
  },
);
