# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations
from typing import Annotated, Literal
from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, EmailStr, Field, RootModel
from uuid import UUID
from datetime import date as date_aliased


class ValidationIssue(BaseModel):
    loc: Annotated[list[str | int], Field(description='Ruta del campo (`["body", "equipment", "items", 0]`).')]
    msg: Annotated[str, Field(description='Mensaje en el idioma del usuario.')]
    type: Annotated[str, Field(description='Tipo de error estable (`missing`, `too_short`…).')]


class ExerciseIdValue(RootModel[str]):
    root: Annotated[str, Field(description='Id del dataset de origen, cuatro dígitos con ceros a la izquierda.', examples=['0043'], pattern='^[0-9]{4}$')]


class HealthStatus(BaseModel):
    status: Literal['ok']


class Checks(BaseModel):
    database: bool
    media: Annotated[bool, Field(description='`$MEDIA_ROOT/manifest.json` legible.')]


class ReadinessStatus(BaseModel):
    status: Literal['ready', 'not_ready']
    checks: Checks


class MediaAttribution(BaseModel):
    text: Literal['© Gym visual']
    url: Literal['https://gymvisual.com/']


class Dataset(BaseModel):
    repo: Annotated[AnyUrl, Field(examples=['https://github.com/hasaneyldrm/exercises-dataset'])]
    commit: Annotated[str, Field(examples=['7455efae41b330c265e7cd4b78dfa848e7ce5ebd'], pattern='^[0-9a-f]{40}$')]
    ingested_at: AwareDatetime | None
    exercise_count: Annotated[int, Field(examples=[1324], ge=0)]


class Licenses(BaseModel):
    dataset_mit: Annotated[str, Field(description='Texto completo de la licencia MIT del dataset.')]
    media_notice: Annotated[str, Field(description='Aviso de medios de Gym visual (NOTICE.md del dataset).')]


class AboutInfo(BaseModel):
    app_version: Annotated[str, Field(examples=['1.0.0'])]
    api_version: Annotated[str, Field(examples=['1.0.0'])]
    engine_version: Annotated[str, Field(examples=['1.0.0'])]
    nutrition_version: Annotated[str, Field(examples=['1.0.0'])]
    dataset: Dataset
    licenses: Licenses
    media_attribution: MediaAttribution
    health_disclaimer_es: Annotated[str, Field(examples=['Forja no sustituye el consejo de profesionales sanitarios ni de entrenamiento.'])]


class MuscleRegion(RootModel[Literal['upper', 'lower', 'core', 'cardio', 'other']]):
    root: Literal['upper', 'lower', 'core', 'cardio', 'other']


class RegisterRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    email: Annotated[EmailStr, Field(max_length=254)]
    password: Annotated[str, Field(description='Mínimo 10 caracteres; se rechazan contraseñas comunes (lista local).', max_length=256, min_length=10)]
    display_name: Annotated[str, Field(max_length=60, min_length=1)]
    locale: Literal['es', 'en'] | None = None


class LoginRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    email: Annotated[EmailStr, Field(max_length=254)]
    password: Annotated[str, Field(max_length=256, min_length=1)]


class PasswordChangeRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    current_password: Annotated[str, Field(max_length=256, min_length=1)]
    new_password: Annotated[str, Field(max_length=256, min_length=10)]


class CurrentUser(BaseModel):
    id: UUID
    email: EmailStr
    display_name: str
    role: Literal['user', 'admin']
    locale: Literal['es', 'en']
    units: Literal['metric', 'imperial']
    created_at: AwareDatetime
    last_login_at: AwareDatetime | None
    onboarding_completed: Annotated[bool, Field(description='Perfil básico y PAR-Q completados.')]
    diet_available: Annotated[bool, Field(description='`DIET_FEATURE_ENABLED` global y `diet_enabled` del usuario.')]


class AuthSession(BaseModel):
    id: UUID
    created_at: AwareDatetime
    last_seen_at: AwareDatetime
    expires_at: AwareDatetime
    user_agent: Annotated[str | None, Field(max_length=256)]
    current: Annotated[bool, Field(description='Es la sesión de esta petición.')]


class AuthSessionList(BaseModel):
    items: list[AuthSession]


class EquipmentSelection(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    preset: Literal['full_gym', 'home_dumbbells', 'home_bands', 'bodyweight', 'custom']
    items: list[Literal['bodyweight', 'dumbbell', 'cable', 'barbell', 'ez_bar', 'trap_bar', 'machine', 'smith', 'sled', 'assisted', 'band', 'kettlebell', 'weighted', 'stability_ball', 'medicine_ball', 'bosu', 'rope', 'roller', 'ab_wheel', 'hammer', 'tire', 'arm_ergometer', 'skierg', 'bike', 'elliptical', 'stepmill']]


class Limitations(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    avoid_muscles: list[Literal['chest', 'lats', 'upper_back', 'traps', 'lower_back', 'shoulders', 'rear_delts', 'rotator_cuff', 'serratus', 'biceps', 'triceps', 'forearms', 'abs', 'obliques', 'hip_flexors', 'glutes', 'quads', 'hamstrings', 'adductors', 'abductors', 'calves', 'lower_leg', 'neck', 'cardio']]
    avoid_patterns: list[Literal['squat', 'lunge', 'hinge', 'horizontal_push', 'vertical_push', 'horizontal_pull', 'vertical_pull', 'elbow_flexion', 'elbow_extension', 'shoulder_raise', 'chest_fly', 'rear_delt', 'knee_extension', 'knee_flexion', 'hip_abduction', 'hip_adduction', 'glute_isolation', 'calf', 'core_flexion', 'core_anti_extension', 'core_rotation', 'core_lateral', 'shrug', 'forearm', 'neck', 'carry', 'plyometric', 'cardio', 'mobility', 'other']]
    notes: Annotated[str | None, Field(description='Texto libre; dato sensible, nunca en logs.', max_length=500)]


class Preferences(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    theme: Literal['dark', 'light', 'system']
    sounds: bool
    vibration: bool
    default_rest_s: Annotated[int | None, Field(description='Descanso por defecto en sesiones libres; `null` usa el del programa.', ge=15, le=600)]


class ProfileFields(BaseModel):
    display_name: Annotated[str, Field(max_length=60, min_length=1)]
    locale: Literal['es', 'en']
    units: Literal['metric', 'imperial']
    sex: Literal['male', 'female', 'unspecified']
    birth_date: date_aliased | None
    height_cm: Annotated[float | None, Field(ge=100.0, le=250.0)]
    experience: Literal['beginner', 'intermediate', 'advanced']
    activity_level: Literal['sedentary', 'light', 'moderate', 'high']
    equipment: EquipmentSelection
    limitations: Limitations
    diet_enabled: bool
    preferences: Preferences


class ProfileUpdate(ProfileFields):
    model_config = ConfigDict(
        extra='forbid',
    )


class Profile(ProfileFields):
    parq_flagged: bool
    parq_completed_at: AwareDatetime | None
    onboarding_completed: bool
    updated_at: AwareDatetime


class ParqAnswers(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    heart_condition: bool
    chest_pain_activity: bool
    chest_pain_rest: bool
    dizziness_or_fainting: bool
    bone_or_joint_problem: bool
    blood_pressure_or_heart_medication: bool
    other_reason: bool


class ParqSubmission(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    answers: ParqAnswers


class ParqResult(BaseModel):
    parq_flagged: bool
    experience_forced: Annotated[bool, Field(description='Se ha fijado `experience = beginner`.')]
    recommendation_es: Annotated[str | None, Field(examples=['Te recomendamos consultar con un profesional sanitario antes de empezar. Hemos ajustado tu nivel a principiante; puedes cambiarlo en tu perfil.'])]
    profile: Profile


class BodyMetricCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    date: date_aliased
    weight_kg: Annotated[float, Field(ge=20.0, le=400.0)]
    body_fat_pct: Annotated[float | None, Field(ge=2.0, le=70.0)] = None
    waist_cm: Annotated[float | None, Field(ge=30.0, le=250.0)] = None


class BodyMetric(BaseModel):
    id: UUID
    date: date_aliased
    weight_kg: float
    body_fat_pct: float | None
    waist_cm: float | None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class BodyMetricPage(BaseModel):
    items: list[BodyMetric]
    next_cursor: str | None


class ExerciseMedia(BaseModel):
    thumb_url: Annotated[str, Field(examples=['/media/thumbs/0043-qXTaZnJ.jpg'])]
    gif_url: Annotated[str, Field(examples=['/media/gifs/0043-qXTaZnJ.gif'])]
    width: Literal[180]
    height: Literal[180]
    attribution: MediaAttribution


class ExerciseSummary(BaseModel):
    id: Annotated[str, Field(description='Id del dataset de origen, cuatro dígitos con ceros a la izquierda.', examples=['0043'], pattern='^[0-9]{4}$')]
    slug: Annotated[str, Field(pattern='^[a-z0-9]+(?:-[a-z0-9]+)*$')]
    name_es: Annotated[str, Field(description='Nombre en español (minúscula inicial; el cliente capitaliza).')]
    name_en: Annotated[str, Field(description='`display_name_en` (erratas corregidas, sin sufijos de variante).')]
    variant_label_es: Annotated[str | None, Field(description='Etiqueta de variante («variante 2», «vista lateral», «(variante B)»).')]
    body_part: Annotated[Literal['upper_arms', 'upper_legs', 'back', 'waist', 'chest', 'shoulders', 'lower_legs', 'lower_arms', 'cardio', 'neck'], Field(description='`body_part` del dataset normalizado a snake_case.')]
    equipment_code: Annotated[Literal['bodyweight', 'dumbbell', 'cable', 'barbell', 'ez_bar', 'trap_bar', 'machine', 'smith', 'sled', 'assisted', 'band', 'kettlebell', 'weighted', 'stability_ball', 'medicine_ball', 'bosu', 'rope', 'roller', 'ab_wheel', 'hammer', 'tire', 'arm_ergometer', 'skierg', 'bike', 'elliptical', 'stepmill'], Field(description='Código canónico de `specs/equipment-normalization.yaml`.')]
    target_muscle: Annotated[Literal['chest', 'lats', 'upper_back', 'traps', 'lower_back', 'shoulders', 'rear_delts', 'rotator_cuff', 'serratus', 'biceps', 'triceps', 'forearms', 'abs', 'obliques', 'hip_flexors', 'glutes', 'quads', 'hamstrings', 'adductors', 'abductors', 'calves', 'lower_leg', 'neck', 'cardio'], Field(description='Código canónico de `specs/muscle-normalization.yaml`.')]
    movement_pattern: Literal['squat', 'lunge', 'hinge', 'horizontal_push', 'vertical_push', 'horizontal_pull', 'vertical_pull', 'elbow_flexion', 'elbow_extension', 'shoulder_raise', 'chest_fly', 'rear_delt', 'knee_extension', 'knee_flexion', 'hip_abduction', 'hip_adduction', 'glute_isolation', 'calf', 'core_flexion', 'core_anti_extension', 'core_rotation', 'core_lateral', 'shrug', 'forearm', 'neck', 'carry', 'plyometric', 'cardio', 'mobility', 'other']
    mechanic: Literal['compound', 'isolation']
    role: Literal['main', 'accessory', 'core', 'cardio', 'mobility', 'warmup']
    difficulty: Annotated[int, Field(description='1 = guiado/asistido, 2 = estándar, 3 = exigente (unilateral, gimnástico, olímpico).', ge=1, le=3)]
    is_staple: bool
    laterality: Literal['bilateral', 'unilateral']
    load_type: Literal['external', 'bodyweight', 'assisted', 'time']
    demo_sex: Literal['male', 'female'] | None
    variant_group: str
    media: ExerciseMedia
    is_favorite: bool
    deprecated: Annotated[bool, Field(description='Retirado del dataset; se conserva por historial.')]


class ExerciseInstructions(BaseModel):
    lang: Literal['en', 'es', 'it', 'tr', 'ru', 'zh', 'hi', 'pl', 'ko', 'fr']
    text: str
    steps: Annotated[list[str], Field(min_length=1)]


class ExerciseVariantRef(BaseModel):
    id: Annotated[str, Field(description='Id del dataset de origen, cuatro dígitos con ceros a la izquierda.', examples=['0043'], pattern='^[0-9]{4}$')]
    name_es: str
    label_es: Annotated[str, Field(examples=['vista trasera'])]
    kind: Annotated[Literal['version', 'demonstrator', 'camera_angle', 'duplicate'], Field(description='version = `v. N`; demonstrator = `(male)`/`(female)`; camera_angle = `(back pov)`/`(side pov)`; duplicate = mismo nombre con distinto id.')]
    demo_sex: Literal['male', 'female'] | None


class ExerciseDetail(ExerciseSummary):
    secondary_muscles: list[Literal['chest', 'lats', 'upper_back', 'traps', 'lower_back', 'shoulders', 'rear_delts', 'rotator_cuff', 'serratus', 'biceps', 'triceps', 'forearms', 'abs', 'obliques', 'hip_flexors', 'glutes', 'quads', 'hamstrings', 'adductors', 'abductors', 'calves', 'lower_leg', 'neck', 'cardio']]
    primary_group_muscle: Annotated[Literal['chest', 'lats', 'upper_back', 'traps', 'lower_back', 'shoulders', 'rear_delts', 'rotator_cuff', 'serratus', 'biceps', 'triceps', 'forearms', 'abs', 'obliques', 'hip_flexors', 'glutes', 'quads', 'hamstrings', 'adductors', 'abductors', 'calves', 'lower_leg', 'neck', 'cardio'], Field(description='Código canónico de `specs/muscle-normalization.yaml`.')]
    equipment_group: Literal['gym', 'home_basic', 'bodyweight', 'cardio_machine', 'other']
    instructions: ExerciseInstructions
    available_langs: list[Literal['en', 'es', 'it', 'tr', 'ru', 'zh', 'hi', 'pl', 'ko', 'fr']]
    variants: Annotated[list[ExerciseVariantRef], Field(description='Otros ejercicios del mismo `variant_group` (conmutador de ángulo/demostrador).')]
    source_commit: Annotated[str, Field(pattern='^[0-9a-f]{40}$')]
    enrichment_version: Annotated[int, Field(ge=1)]
    deprecated_at: AwareDatetime | None


class ExercisePage(BaseModel):
    items: list[ExerciseSummary]
    next_cursor: str | None


class ExerciseAlternative(BaseModel):
    exercise: ExerciseSummary
    score: Annotated[float, Field(description='Puntuación §6.5 (patrón 0,5 + músculo 0,3 + Jaccard 0,1 + dificultad 0,1).', ge=0.0, le=1.0)]


class ExerciseAlternativeList(BaseModel):
    items: Annotated[list[ExerciseAlternative], Field(max_length=8)]


class FacetValue(BaseModel):
    value: Annotated[str, Field(description='Valor del filtro (código canónico o dificultad como texto).')]
    label_es: str
    label_en: str
    count: Annotated[int, Field(ge=0)]


class CatalogFacets(BaseModel):
    total: Annotated[int, Field(ge=0)]
    body_part: list[FacetValue]
    target: list[FacetValue]
    muscle: list[FacetValue]
    equipment: list[FacetValue]
    pattern: list[FacetValue]
    mechanic: list[FacetValue]
    difficulty: list[FacetValue]
    role: list[FacetValue]


class ExerciseCard(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(description='Id del dataset de origen, cuatro dígitos con ceros a la izquierda.', examples=['0043'], pattern='^[0-9]{4}$')]
    name_es: str
    display_name_en: str
    variant_group: str
    body_part: Annotated[Literal['upper_arms', 'upper_legs', 'back', 'waist', 'chest', 'shoulders', 'lower_legs', 'lower_arms', 'cardio', 'neck'], Field(description='`body_part` del dataset normalizado a snake_case.')]
    equipment_code: Annotated[Literal['bodyweight', 'dumbbell', 'cable', 'barbell', 'ez_bar', 'trap_bar', 'machine', 'smith', 'sled', 'assisted', 'band', 'kettlebell', 'weighted', 'stability_ball', 'medicine_ball', 'bosu', 'rope', 'roller', 'ab_wheel', 'hammer', 'tire', 'arm_ergometer', 'skierg', 'bike', 'elliptical', 'stepmill'], Field(description='Código canónico de `specs/equipment-normalization.yaml`.')]
    equipment_group: Literal['gym', 'home_basic', 'bodyweight', 'cardio_machine', 'other']
    target_muscle: Annotated[Literal['chest', 'lats', 'upper_back', 'traps', 'lower_back', 'shoulders', 'rear_delts', 'rotator_cuff', 'serratus', 'biceps', 'triceps', 'forearms', 'abs', 'obliques', 'hip_flexors', 'glutes', 'quads', 'hamstrings', 'adductors', 'abductors', 'calves', 'lower_leg', 'neck', 'cardio'], Field(description='Código canónico de `specs/muscle-normalization.yaml`.')]
    primary_group_muscle: Annotated[Literal['chest', 'lats', 'upper_back', 'traps', 'lower_back', 'shoulders', 'rear_delts', 'rotator_cuff', 'serratus', 'biceps', 'triceps', 'forearms', 'abs', 'obliques', 'hip_flexors', 'glutes', 'quads', 'hamstrings', 'adductors', 'abductors', 'calves', 'lower_leg', 'neck', 'cardio'], Field(description='Código canónico de `specs/muscle-normalization.yaml`.')]
    secondary_muscles: list[Literal['chest', 'lats', 'upper_back', 'traps', 'lower_back', 'shoulders', 'rear_delts', 'rotator_cuff', 'serratus', 'biceps', 'triceps', 'forearms', 'abs', 'obliques', 'hip_flexors', 'glutes', 'quads', 'hamstrings', 'adductors', 'abductors', 'calves', 'lower_leg', 'neck', 'cardio']]
    movement_pattern: Literal['squat', 'lunge', 'hinge', 'horizontal_push', 'vertical_push', 'horizontal_pull', 'vertical_pull', 'elbow_flexion', 'elbow_extension', 'shoulder_raise', 'chest_fly', 'rear_delt', 'knee_extension', 'knee_flexion', 'hip_abduction', 'hip_adduction', 'glute_isolation', 'calf', 'core_flexion', 'core_anti_extension', 'core_rotation', 'core_lateral', 'shrug', 'forearm', 'neck', 'carry', 'plyometric', 'cardio', 'mobility', 'other']
    mechanic: Literal['compound', 'isolation']
    role: Literal['main', 'accessory', 'core', 'cardio', 'mobility', 'warmup']
    difficulty: Annotated[int, Field(description='1 = guiado/asistido, 2 = estándar, 3 = exigente (unilateral, gimnástico, olímpico).', ge=1, le=3)]
    is_staple: bool
    laterality: Literal['bilateral', 'unilateral']
    load_type: Literal['external', 'bodyweight', 'assisted', 'time']
    demo_sex: Literal['male', 'female'] | None
    deprecated: bool


class GeneratorInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    goal: Literal['strength', 'hypertrophy', 'fat_loss', 'endurance', 'general_fitness', 'toning']
    days_per_week: Annotated[int, Field(ge=1, le=7)]
    sex: Literal['male', 'female', 'unspecified']
    experience: Literal['beginner', 'intermediate', 'advanced']
    session_minutes: Annotated[int, Field(ge=20, le=120, multiple_of=5)]
    equipment: EquipmentSelection
    emphasis: Literal['balanced', 'lower_glutes', 'upper_body', 'arms', 'back_posture', 'core'] | None = 'balanced'
    avoid_muscles: list[Literal['chest', 'lats', 'upper_back', 'traps', 'lower_back', 'shoulders', 'rear_delts', 'rotator_cuff', 'serratus', 'biceps', 'triceps', 'forearms', 'abs', 'obliques', 'hip_flexors', 'glutes', 'quads', 'hamstrings', 'adductors', 'abductors', 'calves', 'lower_leg', 'neck', 'cardio']] | None = []
    avoid_patterns: list[Literal['squat', 'lunge', 'hinge', 'horizontal_push', 'vertical_push', 'horizontal_pull', 'vertical_pull', 'elbow_flexion', 'elbow_extension', 'shoulder_raise', 'chest_fly', 'rear_delt', 'knee_extension', 'knee_flexion', 'hip_abduction', 'hip_adduction', 'glute_isolation', 'calf', 'core_flexion', 'core_anti_extension', 'core_rotation', 'core_lateral', 'shrug', 'forearm', 'neck', 'carry', 'plyometric', 'cardio', 'mobility', 'other']] | None = []
    preferred_days: Annotated[list[Literal['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']] | None, Field(description='Vacía o con exactamente `days_per_week` elementos.', max_length=7)] = []
    weeks: Annotated[int | None, Field(description='Incluye la semana final de descarga.', ge=4, le=8)] = 5
    include_warmup: Annotated[bool | None, Field(description='`null` ⇒ valor por defecto según objetivo.')] = None
    include_cooldown: bool | None = None
    include_cardio_finisher: bool | None = None
    favorite_exercise_ids: Annotated[list[ExerciseIdValue] | None, Field(max_length=200, validate_default=True)] = []
    excluded_exercise_ids: Annotated[list[ExerciseIdValue] | None, Field(max_length=500, validate_default=True)] = []
    seed: Annotated[int | None, Field(description='Entero seguro en JavaScript (≤ 2^53−1). `null` ⇒ se deriva del hash de la entrada normalizada.', ge=0, le=9007199254740991)] = None


class SlotRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    slot_index: Annotated[int, Field(ge=0)]
    pattern: Literal['squat', 'lunge', 'hinge', 'horizontal_push', 'vertical_push', 'horizontal_pull', 'vertical_pull', 'elbow_flexion', 'elbow_extension', 'shoulder_raise', 'chest_fly', 'rear_delt', 'knee_extension', 'knee_flexion', 'hip_abduction', 'hip_adduction', 'glute_isolation', 'calf', 'core_flexion', 'core_anti_extension', 'core_rotation', 'core_lateral', 'shrug', 'forearm', 'neck', 'carry', 'plyometric', 'cardio', 'mobility', 'other']
    role: Literal['main', 'accessory', 'core', 'cardio', 'mobility', 'warmup']
    group: Annotated[Literal['chest', 'back', 'shoulders', 'arms', 'quads', 'hamstrings', 'glutes', 'calves', 'core', 'legs_other', 'other', 'cardio'], Field(description='Grupo de un slot del split; `legs_other`, `other` y `cardio` no computan volumen.')]
    priority: Annotated[int, Field(ge=1, le=3)]


class SlotAddress(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    week_index: Annotated[int, Field(ge=0)]
    day_index: Annotated[int, Field(ge=0, le=6)]
    block_order: Annotated[int, Field(ge=0)]
    exercise_order: Annotated[int, Field(ge=0)]


class PlanWarning(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Annotated[Literal['beginner_high_frequency', 'recovery_day_enforced', 'slot_relaxed', 'slot_dropped', 'time_budget_exceeded', 'main_exercise_trimmed', 'volume_out_of_range', 'session_group_cap', 'rest_below_minimum', 'empty_day', 'mobility_in_main_block', 'equipment_insufficient', 'avoided_muscle_substituted', 'deprecated_exercise', 'excluded_exercise', 'avoided_exercise', 'unknown_exercise'], Field(description='Códigos estables de aviso del motor (ampliables vía CONTRACT_CHANGES).')]
    message_es: str
    week_index: Annotated[int | None, Field(ge=0)]
    day_index: Annotated[int | None, Field(ge=0, le=6)]
    exercise_id: ExerciseIdValue | None


class GroupVolume(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    group: Annotated[Literal['chest', 'back', 'shoulders', 'arms', 'quads', 'hamstrings', 'glutes', 'calves', 'core'], Field(description='Grupos que computan volumen semanal (`specs/volume-targets.yaml`).')]
    target_min: Annotated[float, Field(ge=0.0)]
    target_max: Annotated[float, Field(ge=0.0)]
    planned_sets: Annotated[float, Field(description='Compuestos: 1,0 al objetivo y 0,5 a secundarios relevantes.', ge=0.0)]


class GroupSets(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    group: Annotated[Literal['chest', 'back', 'shoulders', 'arms', 'quads', 'hamstrings', 'glutes', 'calves', 'core'], Field(description='Grupos que computan volumen semanal (`specs/volume-targets.yaml`).')]
    sets: Annotated[float, Field(description='Máx. 10 series efectivas por grupo y sesión.', ge=0.0, le=10.0)]


class ExercisePrescription(BaseModel):
    exercise_id: Annotated[str, Field(description='Id del dataset de origen, cuatro dígitos con ceros a la izquierda.', examples=['0043'], pattern='^[0-9]{4}$')]
    sets: Annotated[int, Field(ge=1, le=10)]
    rep_min: Annotated[int | None, Field(ge=1, le=100)]
    rep_max: Annotated[int | None, Field(ge=1, le=100)]
    duration_s: Annotated[int | None, Field(ge=5, le=3600)]
    per_side: bool
    target_rir: Annotated[int | None, Field(ge=0, le=5)]
    tempo: Annotated[str | None, Field(examples=['3-0-1-0'], pattern='^[0-9X]-[0-9X]-[0-9X]-[0-9X]$')]
    rest_s: Annotated[int, Field(ge=0, le=600)]
    load_hint: Annotated[str | None, Field(examples=['Carga que te deje 2 repeticiones en reserva'], max_length=200)]
    notes_es: Annotated[str | None, Field(max_length=500)]
    alternatives: Annotated[list[ExerciseIdValue], Field(max_length=3)]


class PlanExercise(ExercisePrescription):
    order: Annotated[int, Field(ge=0)]
    slot: Annotated[SlotRef | None, Field(description='`null` en ejercicios de calentamiento, vuelta a la calma o finisher.')]


class PlanBlock(BaseModel):
    order: Annotated[int, Field(ge=0)]
    kind: Literal['warmup', 'main', 'superset', 'circuit', 'finisher', 'cooldown']
    rounds: Annotated[int, Field(ge=1, le=10)]
    rest_between_rounds_s: Annotated[int | None, Field(ge=0, le=600)]
    exercises: Annotated[list[PlanExercise], Field(min_length=1)]


class PlanDay(BaseModel):
    index: Annotated[int, Field(ge=0, le=6)]
    template: Annotated[str, Field(description='Clave de `day_templates` en `specs/split-templates.yaml`.', examples=['upper_a'])]
    name_es: Annotated[str, Field(examples=['Torso A'])]
    focus_es: Annotated[str, Field(examples=['Tren superior: empuje y tirón horizontal'])]
    weekday: Literal['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'] | None
    is_recovery: Annotated[bool, Field(description='Día de recuperación activa (7 días/semana).')]
    estimated_minutes: Annotated[int, Field(ge=1, le=240)]
    blocks: Annotated[list[PlanBlock], Field(min_length=1)]
    volume: list[GroupSets]


class PlanWeek(BaseModel):
    index: Annotated[int, Field(ge=0, le=7)]
    phase: Literal['accumulation', 'intensification', 'deload']
    target_rir: Annotated[int, Field(description='RIR objetivo de referencia de la semana.', ge=0, le=5)]
    volume_ratio: Annotated[float, Field(description='1,0 normal; ≈0,55 en descarga.', gt=0.0, le=2.0)]
    days: Annotated[list[PlanDay], Field(max_length=7, min_length=1)]


class ProgramPlan(BaseModel):
    engine_version: Annotated[str, Field(examples=['1.0.0'])]
    tables_hash: Annotated[str, Field(description='SHA-256 de las tablas YAML cargadas.', pattern='^[0-9a-f]{64}$')]
    seed: Annotated[int, Field(ge=0, le=9007199254740991)]
    input: GeneratorInput
    split: Annotated[list[str], Field(description='Plantillas de día elegidas, en orden.', max_length=7, min_length=1)]
    weeks: Annotated[list[PlanWeek], Field(max_length=8, min_length=4)]
    weekly_volume: list[GroupVolume]
    warnings: list[PlanWarning]
    rationale_es: Annotated[list[str], Field(examples=[['Hemos elegido torso/pierna porque entrenas 4 días y tienes experiencia intermedia.', 'Hemos dado más volumen a glúteos e isquios por el énfasis elegido.']])]


class GeneratorPreview(BaseModel):
    plan: ProgramPlan
    exercises: Annotated[list[ExerciseSummary], Field(description='Ejercicios referenciados por el plan (incluidas alternativas), sin repetir.')]


class PreviewRegenerateDayRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    plan: ProgramPlan
    day_index: Annotated[int, Field(ge=0, le=6)]
    seed: Annotated[int | None, Field(description='`null` ⇒ semilla nueva derivada.', ge=0, le=9007199254740991)]


class PreviewSwapRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    plan: ProgramPlan
    address: SlotAddress
    exclude_ids: Annotated[list[ExerciseIdValue], Field(max_length=100)]
    replacement_id: Annotated[ExerciseIdValue | None, Field(description='Ejercicio elegido por el usuario; `null` ⇒ el motor elige el mejor candidato.')]
    apply_to_all_weeks: bool


class ProgramExercise(ExercisePrescription):
    id: UUID
    order: Annotated[int, Field(ge=0)]


class ProgramBlock(BaseModel):
    id: UUID
    order: Annotated[int, Field(ge=0)]
    kind: Literal['warmup', 'main', 'superset', 'circuit', 'finisher', 'cooldown']
    rounds: Annotated[int, Field(ge=1, le=10)]
    rest_between_rounds_s: Annotated[int | None, Field(ge=0, le=600)]
    exercises: Annotated[list[ProgramExercise], Field(min_length=1)]


class ProgramDay(BaseModel):
    id: UUID
    index: Annotated[int, Field(ge=0, le=6)]
    name: Annotated[str, Field(max_length=80)]
    focus: Annotated[str | None, Field(max_length=120)]
    weekday: Literal['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'] | None
    is_recovery: bool
    estimated_minutes: Annotated[int, Field(ge=1, le=240)]
    blocks: list[ProgramBlock]


class ProgramWeek(BaseModel):
    id: UUID
    index: Annotated[int, Field(ge=0, le=7)]
    phase: Literal['accumulation', 'intensification', 'deload']
    days: list[ProgramDay]


class ProgramSummary(BaseModel):
    id: UUID
    name: Annotated[str, Field(max_length=80)]
    source: Literal['generated', 'manual', 'imported']
    goal: Literal['strength', 'hypertrophy', 'fat_loss', 'endurance', 'general_fitness', 'toning'] | None
    days_per_week: Annotated[int, Field(ge=1, le=7)]
    weeks_count: Annotated[int, Field(ge=1, le=8)]
    is_active: bool
    archived_at: AwareDatetime | None
    generator_version: Annotated[str | None, Field(description='`ENGINE_VERSION` con el que se generó.')]
    created_at: AwareDatetime
    updated_at: AwareDatetime


class ProgramDetail(ProgramSummary):
    seed: Annotated[int | None, Field(ge=0, le=9007199254740991)]
    tables_hash: Annotated[str | None, Field(pattern='^[0-9a-f]{64}$')]
    generator_input: GeneratorInput | None
    weeks: list[ProgramWeek]
    weekly_volume: list[GroupVolume]
    warnings: list[PlanWarning]
    rationale_es: list[str]
    exercises: Annotated[list[ExerciseSummary], Field(description='Ejercicios referenciados (incluidas alternativas), sin repetir.')]


class ExerciseEdit(ExercisePrescription):
    pass


class BlockEdit(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['warmup', 'main', 'superset', 'circuit', 'finisher', 'cooldown']
    rounds: Annotated[int, Field(ge=1, le=10)]
    rest_between_rounds_s: Annotated[int | None, Field(ge=0, le=600)]
    exercises: Annotated[list[ExerciseEdit], Field(max_length=20, min_length=1)]


class DayEdit(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(max_length=80, min_length=1)]
    focus: Annotated[str | None, Field(max_length=120)]
    weekday: Literal['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'] | None
    blocks: Annotated[list[BlockEdit], Field(max_length=12, min_length=1)]
    apply_to_all_weeks: Annotated[bool, Field(description='Propaga la estructura al mismo día del resto de semanas (re-periodizado por el motor).')]


class ProgramCreateFromPlan(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Literal['generated']
    name: Annotated[str, Field(max_length=80, min_length=1)]
    plan: ProgramPlan
    activate: bool


class ProgramCreateManual(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Literal['manual']
    name: Annotated[str, Field(max_length=80, min_length=1)]
    goal: Literal['strength', 'hypertrophy', 'fat_loss', 'endurance', 'general_fitness', 'toning'] | None
    weeks: Annotated[int, Field(description='Número de semanas; la estructura de `days` se repite en todas.', ge=1, le=8)]
    days: Annotated[list[DayEdit], Field(max_length=7, min_length=1)]
    activate: bool


class ProgramCreate(RootModel[ProgramCreateFromPlan | ProgramCreateManual]):
    root: Annotated[ProgramCreateFromPlan | ProgramCreateManual, Field(discriminator='source')]


class ProgramUpdate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str | None, Field(max_length=80, min_length=1)] = None
    archived: Annotated[bool | None, Field(description='`true` archiva (y desactiva); `false` desarchiva.')] = None


class ProgramDuplicateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str | None, Field(description='Por defecto «<nombre> (copia)».', max_length=80, min_length=1)] = None


class ProgramPage(BaseModel):
    items: list[ProgramSummary]
    next_cursor: str | None


class RegenerateDayRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    day_index: Annotated[int, Field(description='Índice del día en la semana; se regenera en todas las semanas.', ge=0, le=6)]
    seed: Annotated[int | None, Field(ge=0, le=9007199254740991)]


class SwapRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    program_exercise_id: UUID
    exclude_ids: Annotated[list[ExerciseIdValue], Field(max_length=100)]
    replacement_id: ExerciseIdValue | None
    apply_to_all_weeks: bool


class WorkoutSessionCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    client_uuid: Annotated[UUID, Field(description='Generado en el cliente (idempotencia offline).')]
    program_day_id: Annotated[UUID | None, Field(description='`null` ⇒ sesión libre.')]
    name: Annotated[str | None, Field(description='Por defecto, el nombre del día o «Sesión libre».', max_length=80)] = None
    started_at: AwareDatetime
    notes: Annotated[str | None, Field(max_length=2000)] = None


class WorkoutSessionUpdate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str | None, Field(max_length=80, min_length=1)] = None
    notes: Annotated[str | None, Field(max_length=2000)] = None
    perceived_effort: Annotated[int | None, Field(ge=1, le=10)] = None
    status: Annotated[Literal['abandoned'] | None, Field(description='Solo se puede pasar a `abandoned`; para terminar, `/finish`.')] = None


class SetLogCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    client_uuid: UUID
    exercise_id: Annotated[str, Field(description='Id del dataset de origen, cuatro dígitos con ceros a la izquierda.', examples=['0043'], pattern='^[0-9]{4}$')]
    program_exercise_id: UUID | None
    set_index: Annotated[int, Field(ge=1, le=50)]
    weight_kg: Annotated[float | None, Field(description='Siempre en kg (el cliente convierte si `units = imperial`).', ge=0.0, le=1000.0)]
    reps: Annotated[int | None, Field(ge=0, le=200)]
    rir: Annotated[int | None, Field(ge=0, le=10)]
    duration_s: Annotated[int | None, Field(ge=1, le=7200)]
    is_warmup: bool
    completed_at: AwareDatetime


class SetLogUpdate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    weight_kg: Annotated[float | None, Field(ge=0.0, le=1000.0)] = None
    reps: Annotated[int | None, Field(ge=0, le=200)] = None
    rir: Annotated[int | None, Field(ge=0, le=10)] = None
    duration_s: Annotated[int | None, Field(ge=1, le=7200)] = None
    is_warmup: bool | None = None


class SetLog(BaseModel):
    id: UUID
    client_uuid: UUID
    session_id: UUID
    exercise_id: Annotated[str, Field(description='Id del dataset de origen, cuatro dígitos con ceros a la izquierda.', examples=['0043'], pattern='^[0-9]{4}$')]
    program_exercise_id: UUID | None
    set_index: Annotated[int, Field(ge=1)]
    weight_kg: float | None
    reps: int | None
    rir: int | None
    duration_s: int | None
    is_warmup: bool
    completed_at: AwareDatetime
    updated_at: AwareDatetime
    records: Annotated[list[Literal['e1rm', 'heaviest_set', 'volume']], Field(description='Récords personales que ha batido esta serie (para el confeti discreto).')]


class WorkoutSessionSummary(BaseModel):
    id: UUID
    client_uuid: UUID
    program_id: UUID | None
    program_day_id: UUID | None
    name: str
    started_at: AwareDatetime
    finished_at: AwareDatetime | None
    status: Literal['in_progress', 'completed', 'abandoned']
    perceived_effort: Annotated[int | None, Field(ge=1, le=10)]
    notes: str | None
    set_count: Annotated[int, Field(description='Series de trabajo (sin calentamiento).', ge=0)]
    volume_kg: Annotated[float, Field(description='Σ peso × reps de las series de trabajo.', ge=0.0)]
    created_at: AwareDatetime
    updated_at: AwareDatetime


class WorkoutSession(WorkoutSessionSummary):
    sets: list[SetLog]


class WorkoutSessionPage(BaseModel):
    items: list[WorkoutSessionSummary]
    next_cursor: str | None


class SessionFinishRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    finished_at: AwareDatetime
    perceived_effort: Annotated[int | None, Field(ge=1, le=10)] = None
    notes: Annotated[str | None, Field(max_length=2000)] = None


class SyncSessionUpsert(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    op: Literal['session_upsert']
    client_uuid: UUID
    program_day_id: UUID | None
    name: Annotated[str | None, Field(max_length=80)]
    started_at: AwareDatetime
    finished_at: AwareDatetime | None
    status: Literal['in_progress', 'completed', 'abandoned']
    perceived_effort: Annotated[int | None, Field(ge=1, le=10)]
    notes: Annotated[str | None, Field(max_length=2000)]
    updated_at: Annotated[AwareDatetime, Field(description='Marca del cliente para «última escritura gana».')]


class SyncSetUpsert(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    op: Literal['set_upsert']
    session_client_uuid: UUID
    set: SetLogCreate
    updated_at: AwareDatetime


class SyncSetDelete(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    op: Literal['set_delete']
    client_uuid: Annotated[UUID, Field(description='`client_uuid` de la serie.')]
    deleted_at: AwareDatetime


class SyncRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    operations: Annotated[list[Annotated[SyncSessionUpsert | SyncSetUpsert | SyncSetDelete, Field(discriminator='op')]], Field(max_length=500, min_length=1)]


class SetPerformance(BaseModel):
    weight_kg: float | None
    reps: int | None
    rir: int | None
    duration_s: int | None


class LastPerformance(BaseModel):
    session_id: UUID
    date: date_aliased
    sets: list[SetPerformance]


class WarmupSet(BaseModel):
    percent: Annotated[float, Field(gt=0.0, le=1.0)]
    reps: Annotated[int, Field(ge=1)]
    weight_kg: Annotated[float, Field(ge=0.0)]
    plates_per_side_kg: Annotated[list[float], Field(description='Discos por lado sobre barra de 20 kg (vacío si no aplica).')]


class LoadSuggestion(BaseModel):
    program_exercise_id: UUID
    exercise_id: Annotated[str, Field(description='Id del dataset de origen, cuatro dígitos con ceros a la izquierda.', examples=['0043'], pattern='^[0-9]{4}$')]
    kind: Literal['first_time', 'increase_load', 'increase_reps', 'harder_variant', 'hold', 'decrease_load']
    suggested_weight_kg: Annotated[float | None, Field(ge=0.0)]
    suggested_rep_min: Annotated[int | None, Field(ge=1)]
    suggested_rep_max: Annotated[int | None, Field(ge=1)]
    suggested_exercise_id: Annotated[ExerciseIdValue | None, Field(description='Variante más difícil del mismo patrón (solo con `harder_variant`).')]
    plates_per_side_kg: list[float]
    reason_es: Annotated[str, Field(examples=['Completaste todas las series en el tope del rango: sube 2,5 kg.'])]
    last_performance: LastPerformance | None
    warmup_sets: list[WarmupSet]


class NextSession(BaseModel):
    status: Literal['scheduled', 'rest_day', 'no_active_program', 'program_completed']
    program_id: UUID | None
    program_name: str | None
    week_index: Annotated[int | None, Field(ge=0)]
    day: ProgramDay | None
    scheduled_date: date_aliased | None
    suggestions: list[LoadSuggestion]
    exercises: list[ExerciseSummary]


class PersonalRecord(BaseModel):
    id: UUID
    exercise_id: Annotated[str, Field(description='Id del dataset de origen, cuatro dígitos con ceros a la izquierda.', examples=['0043'], pattern='^[0-9]{4}$')]
    exercise_name_es: str
    kind: Annotated[Literal['e1rm', 'heaviest_set', 'volume'], Field(description='e1rm = mejor 1RM estimado (Epley); heaviest_set = mejor peso×reps; volume = mayor volumen en una sesión.')]
    value: Annotated[float, Field(description='kg para `e1rm`/`heaviest_set`; kg·reps para `volume`.')]
    weight_kg: float | None
    reps: int | None
    achieved_at: AwareDatetime
    session_id: UUID
    set_id: UUID | None


class PersonalRecordPage(BaseModel):
    items: list[PersonalRecord]
    next_cursor: str | None


class ActivityDay(BaseModel):
    date: date_aliased
    session_count: Annotated[int, Field(ge=1)]
    volume_kg: Annotated[float, Field(ge=0.0)]


class BodyWeight(BaseModel):
    latest: BodyMetric | None
    moving_average_7d_kg: float | None


class StatsOverview(BaseModel):
    week_start: Annotated[date_aliased, Field(description='Lunes de la semana actual (zona del usuario).')]
    sessions_completed: Annotated[int, Field(ge=0)]
    sessions_planned: Annotated[int, Field(ge=0)]
    sets_completed: Annotated[int, Field(ge=0)]
    volume_kg: Annotated[float, Field(ge=0.0)]
    streak_weeks: Annotated[int, Field(description='Semanas consecutivas cumpliendo lo planificado.', ge=0)]
    last_record: PersonalRecord | None
    body_weight: BodyWeight
    activity: Annotated[list[ActivityDay], Field(description='Días con sesiones completadas en los últimos 365 días (mapa de calor).')]


class GroupWeekVolume(BaseModel):
    group: Annotated[Literal['chest', 'back', 'shoulders', 'arms', 'quads', 'hamstrings', 'glutes', 'calves', 'core'], Field(description='Grupos que computan volumen semanal (`specs/volume-targets.yaml`).')]
    effective_sets: Annotated[float, Field(description='Series a RIR ≤ 4 (compuestos 0,5 a secundarios).', ge=0.0)]
    volume_kg: Annotated[float, Field(ge=0.0)]


class VolumeWeek(BaseModel):
    week_start: date_aliased
    groups: list[GroupWeekVolume]


class VolumeStats(BaseModel):
    weeks: list[VolumeWeek]


class ExerciseStatPoint(BaseModel):
    date: date_aliased
    session_id: UUID
    e1rm_kg: Annotated[float | None, Field(description='Epley con reps efectivas (reps + RIR) ≤ 10; `null` si no aplica.')]
    best_weight_kg: float | None
    best_reps: int | None
    volume_kg: Annotated[float, Field(ge=0.0)]


class BestSet(BaseModel):
    weight_kg: float
    reps: int
    rir: int | None
    date: date_aliased


class ExerciseStats(BaseModel):
    exercise_id: Annotated[str, Field(description='Id del dataset de origen, cuatro dígitos con ceros a la izquierda.', examples=['0043'], pattern='^[0-9]{4}$')]
    best_e1rm_kg: float | None
    best_set: BestSet | None
    points: list[ExerciseStatPoint]


class MacroTotals(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kcal: Annotated[float, Field(ge=0.0)]
    protein_g: Annotated[float, Field(ge=0.0)]
    fat_g: Annotated[float, Field(ge=0.0)]
    carbs_g: Annotated[float, Field(ge=0.0)]
    fiber_g: Annotated[float, Field(ge=0.0)]


class NutritionBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    reason_code: Literal['under_18', 'pregnant', 'breastfeeding', 'missing_profile_data']
    message_es: Annotated[str, Field(examples=['No generamos planes de alimentación durante el embarazo o la lactancia. Consulta con un dietista-nutricionista o con tu profesional sanitario.'])]


class NutritionNotice(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Literal['health_disclaimer', 'kcal_floor_applied', 'deficit_capped', 'lose_blocked_low_bmi', 'protein_clamped', 'fat_floor_applied', 'tolerance_not_met', 'swap_macros_adjusted']
    message_es: str


class NutritionTarget(BaseModel):
    method: Literal['mifflin_male', 'mifflin_female', 'mifflin_average']
    age_years: Annotated[int, Field(ge=0)]
    bmr_kcal: Annotated[float, Field(ge=0.0)]
    activity_factor: Annotated[float, Field(ge=1.0, le=1.9)]
    tdee_kcal: Annotated[float, Field(ge=0.0)]
    requested_goal: Literal['lose', 'maintain', 'gain', 'recomp']
    effective_goal: Annotated[Literal['lose', 'maintain', 'gain', 'recomp'], Field(description='Puede diferir del pedido (p. ej. `lose` bloqueado por IMC < 18,5 ⇒ `maintain`).')]
    pace: Literal['gentle', 'standard']
    target_kcal: Annotated[float | None, Field(description='`null` si `blocked`.', ge=0.0)]
    protein_g: Annotated[float | None, Field(ge=0.0)]
    fat_g: Annotated[float | None, Field(ge=0.0)]
    carbs_g: Annotated[float | None, Field(ge=0.0)]
    fiber_g: Annotated[float | None, Field(ge=0.0)]
    blocked: bool
    block: NutritionBlock | None
    notices: list[NutritionNotice]


class NutritionTargetRecord(BaseModel):
    id: UUID
    calculated_at: AwareDatetime
    target: NutritionTarget


class NutritionTargetRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    weight_kg: Annotated[float | None, Field(ge=20.0, le=400.0)] = None
    goal: Literal['lose', 'maintain', 'gain', 'recomp'] | None = None
    pace: Literal['gentle', 'standard'] | None = None


class FoodId(RootModel[str]):
    root: Annotated[str, Field(examples=['garbanzos_cocidos'], max_length=64, pattern='^[a-z0-9]+(?:_[a-z0-9]+)*$')]


class Food(BaseModel):
    id: Annotated[str, Field(examples=['garbanzos_cocidos'], max_length=64, pattern='^[a-z0-9]+(?:_[a-z0-9]+)*$')]
    name_es: str
    category: Annotated[Literal['fruits', 'vegetables', 'legumes', 'grains', 'bakery', 'dairy', 'eggs', 'meat', 'fish_seafood', 'plant_protein', 'nuts_seeds', 'fats_oils', 'condiments', 'beverages'], Field(description='Categoría de supermercado (orden de la lista de la compra).')]
    fdc_id: Annotated[int, Field(description='Identificador de USDA FoodData Central (dominio público).', ge=1)]
    per_100g: MacroTotals
    diet_types: Annotated[list[Literal['omnivore', 'pescatarian', 'vegetarian', 'vegan']], Field(min_length=1)]
    allergens: list[Literal['gluten', 'lactose', 'tree_nuts', 'egg', 'fish', 'shellfish', 'soy', 'peanuts']]
    macro_role: Annotated[Literal['protein', 'carb', 'produce', 'fat'], Field(description='Papel del alimento en las plantillas de comida mediterráneas (§8.3).')]
    typical_portion_g: Annotated[float, Field(gt=0.0)]
    unit_grams: Annotated[float | None, Field(description='Gramos por unidad (huevos, frutas…); `null` si se pesa.', gt=0.0)]
    unit_name_es: Annotated[str | None, Field(examples=['huevo'])]
    energy_note: Annotated[str | None, Field(description='Justificación cuando |kcal − (4P + 4C + 9G)| supera el 12 % (alcohol, fibra, polioles).')]
    max_portion_g: Annotated[float, Field(description='Tope de gramos por ítem en un plan.', gt=0.0)]
    meal_slots: Annotated[list[Literal['breakfast', 'mid_morning', 'lunch', 'snack', 'dinner']], Field(description='Comidas donde puede seleccionarse; vacío = no se selecciona automáticamente.')]
    weekly_max: Annotated[int | None, Field(description='Máximo de apariciones por semana; `null` sin límite.', ge=1)]


class FoodPage(BaseModel):
    items: list[Food]
    next_cursor: str | None


class MealItem(BaseModel):
    food_id: Annotated[str, Field(examples=['garbanzos_cocidos'], max_length=64, pattern='^[a-z0-9]+(?:_[a-z0-9]+)*$')]
    name_es: str
    grams: Annotated[float, Field(description='Múltiplo de 5 g salvo alimentos por unidades.', gt=0.0)]
    units: Annotated[int | None, Field(description='Unidades para alimentos contables.', ge=1)]
    nutrients: MacroTotals


class Meal(BaseModel):
    slot: Literal['breakfast', 'mid_morning', 'lunch', 'snack', 'dinner']
    items: Annotated[list[MealItem], Field(min_length=1)]
    totals: MacroTotals


class MacroDeviation(BaseModel):
    kcal: float
    protein: float
    fat: float
    carbs: float


class MealPlanDay(BaseModel):
    day_index: Annotated[int, Field(ge=0, le=6)]
    date: date_aliased
    meals: Annotated[list[Meal], Field(max_length=5, min_length=3)]
    totals: MacroTotals
    deviation: MacroDeviation


class MealPlan(BaseModel):
    nutrition_version: Annotated[str, Field(examples=['1.0.0'])]
    foods_hash: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]
    seed: Annotated[int, Field(ge=0, le=9007199254740991)]
    week_start: date_aliased
    diet_type: Literal['omnivore', 'pescatarian', 'vegetarian', 'vegan']
    meals_per_day: Annotated[int, Field(ge=3, le=5)]
    target: NutritionTarget
    days: Annotated[list[MealPlanDay], Field(max_length=7, min_length=7)]
    notices: list[NutritionNotice]


class MealPlanCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    week_start: Annotated[date_aliased, Field(description='Lunes de la semana del plan.')]
    seed: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None


class MealPlanResource(BaseModel):
    id: UUID
    created_at: AwareDatetime
    updated_at: AwareDatetime
    plan: MealPlan


class MealPlanSummary(BaseModel):
    id: UUID
    week_start: date_aliased
    diet_type: Literal['omnivore', 'pescatarian', 'vegetarian', 'vegan']
    meals_per_day: Annotated[int, Field(ge=3, le=5)]
    target_kcal: float
    created_at: AwareDatetime


class MealPlanPage(BaseModel):
    items: list[MealPlanSummary]
    next_cursor: str | None


class MealSwapRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    day_index: Annotated[int, Field(ge=0, le=6)]
    meal: Literal['breakfast', 'mid_morning', 'lunch', 'snack', 'dinner']
    food_id: Annotated[str, Field(examples=['garbanzos_cocidos'], max_length=64, pattern='^[a-z0-9]+(?:_[a-z0-9]+)*$')]
    replacement_food_id: Annotated[FoodId | None, Field(description='Alimento elegido (misma categoría); `null` ⇒ el motor elige.')]


class ShoppingItem(BaseModel):
    food_id: Annotated[str, Field(examples=['garbanzos_cocidos'], max_length=64, pattern='^[a-z0-9]+(?:_[a-z0-9]+)*$')]
    name_es: str
    total_grams: Annotated[float, Field(ge=0.0)]
    units: Annotated[int | None, Field(ge=1)]


class ShoppingCategory(BaseModel):
    category: Annotated[Literal['fruits', 'vegetables', 'legumes', 'grains', 'bakery', 'dairy', 'eggs', 'meat', 'fish_seafood', 'plant_protein', 'nuts_seeds', 'fats_oils', 'condiments', 'beverages'], Field(description='Categoría de supermercado (orden de la lista de la compra).')]
    label_es: Annotated[str, Field(examples=['Legumbres'])]
    items: list[ShoppingItem]


class ShoppingList(BaseModel):
    plan_id: UUID
    week_start: date_aliased
    categories: list[ShoppingCategory]


class User(BaseModel):
    email: EmailStr
    display_name: str
    locale: Literal['es', 'en']
    units: Literal['metric', 'imperial']
    created_at: AwareDatetime


class ImportCounts(BaseModel):
    programs: Annotated[int, Field(ge=0)]
    sessions: Annotated[int, Field(ge=0)]
    sets: Annotated[int, Field(ge=0)]
    body_metrics: Annotated[int, Field(ge=0)]
    favorites: Annotated[int, Field(ge=0)]
    meal_plans: Annotated[int, Field(ge=0)]


class ImportResult(BaseModel):
    created: ImportCounts
    skipped: ImportCounts
    warnings: list[str]


class AccountDeleteRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    password: Annotated[str, Field(max_length=256, min_length=1)]


class AdminSettingsFields(BaseModel):
    registration_open: bool
    diet_feature_enabled: bool


class AdminSettingsUpdate(AdminSettingsFields):
    model_config = ConfigDict(
        extra='forbid',
    )


class AdminSettings(AdminSettingsFields):
    media_require_auth: Annotated[bool, Field(description='Efectivo, de `MEDIA_REQUIRE_AUTH` (solo lectura).')]
    dataset_commit: Annotated[str, Field(pattern='^[0-9a-f]{40}$')]


class AdminUser(BaseModel):
    id: UUID
    email: EmailStr
    display_name: str
    role: Literal['user', 'admin']
    is_active: bool
    created_at: AwareDatetime
    last_login_at: AwareDatetime | None


class AdminUserPage(BaseModel):
    items: list[AdminUser]
    next_cursor: str | None


class AdminUserUpdate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    role: Literal['user', 'admin'] | None = None
    is_active: Annotated[bool | None, Field(description='`false` revoca todas sus sesiones.')] = None


class IngestRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dry_run: Annotated[bool, Field(description='Solo calcula el diff (altas/bajas/cambios) sin escribir.')]


class IngestCounts(BaseModel):
    exercises_total: Annotated[int, Field(ge=0)]
    added: Annotated[int, Field(ge=0)]
    updated: Annotated[int, Field(ge=0)]
    deprecated: Annotated[int, Field(ge=0)]
    unchanged: Annotated[int, Field(ge=0)]
    media_verified: Annotated[int, Field(description='Ficheros de medios con SHA-256 verificado (2.648 esperados).', ge=0)]


class IngestDiff(BaseModel):
    added: list[ExerciseIdValue]
    updated: list[ExerciseIdValue]
    deprecated: list[ExerciseIdValue]


class IngestRun(BaseModel):
    id: UUID
    status: Literal['queued', 'running', 'succeeded', 'failed']
    dry_run: bool
    commit: Annotated[str, Field(pattern='^[0-9a-f]{40}$')]
    started_at: AwareDatetime | None
    finished_at: AwareDatetime | None
    triggered_by: Annotated[UUID | None, Field(description='Admin que la lanzó; `null` si fue por CLI.')]
    counts: IngestCounts | None
    diff: IngestDiff | None
    errors: list[str]
    warnings: list[str]


class IngestRunPage(BaseModel):
    items: list[IngestRun]
    next_cursor: str | None


class Problem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Annotated[str, Field(description='URI relativa que identifica el tipo de problema (`/problems/<code-con-guiones>`).')]
    title: Annotated[str, Field(description='Resumen legible en el idioma del usuario.')]
    status: Annotated[int, Field(ge=400, le=599)]
    detail: str | None = None
    instance: str | None = None
    code: Annotated[str, Field(description='Código estable para el cliente. Valores definidos: validation_error, unauthenticated,\ninvalid_credentials, forbidden, csrf_failed, registration_closed, admin_required,\ndiet_disabled, not_found, conflict, email_taken, session_already_finished,\nprogram_not_generated, last_admin, ingest_running, idempotency_key_reused,\nidempotency_in_progress, plan_invalid, nutrition_blocked, payload_too_large,\nimport_invalid, rate_limited, service_unavailable.\n', pattern='^[a-z][a-z0-9_]*$')]
    request_id: Annotated[str | None, Field(description='Identificador de la petición (cabecera `X-Request-ID`).')] = None
    errors: Annotated[list[ValidationIssue] | None, Field(description='Errores de validación por campo (solo con `validation_error`).')] = None
    violations: Annotated[list[PlanWarning] | None, Field(description='Reglas del motor incumplidas (solo con `plan_invalid`).')] = None
    block: Annotated[NutritionBlock | None, Field(description='Bloqueo de seguridad nutricional (solo con `nutrition_blocked`).')] = None


class SessionSummary(BaseModel):
    session: WorkoutSessionSummary
    duration_s: Annotated[int, Field(ge=0)]
    total_sets: Annotated[int, Field(ge=0)]
    total_reps: Annotated[int, Field(ge=0)]
    volume_kg: Annotated[float, Field(ge=0.0)]
    exercises_completed: Annotated[int, Field(ge=0)]
    new_records: list[PersonalRecord]


class SyncResult(BaseModel):
    index: Annotated[int, Field(description='Posición de la operación en el lote.', ge=0)]
    op: Literal['session_upsert', 'set_upsert', 'set_delete']
    client_uuid: UUID
    status: Annotated[Literal['applied', 'duplicate', 'superseded', 'rejected'], Field(description='applied = aplicada; duplicate = ya aplicada antes (reintento); superseded = el servidor tiene una versión más reciente; rejected = inválida (ver `problem`).')]
    server_id: UUID | None
    problem: Problem | None


class SyncResponse(BaseModel):
    server_time: AwareDatetime
    results: list[SyncResult]


class NutritionInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sex: Literal['male', 'female', 'unspecified']
    age_years: Annotated[int, Field(ge=0, le=120)]
    height_cm: Annotated[float, Field(ge=100.0, le=250.0)]
    weight_kg: Annotated[float, Field(ge=20.0, le=400.0)]
    activity_level: Literal['sedentary', 'light', 'moderate', 'high']
    training_days_per_week: Annotated[int, Field(ge=0, le=7)]
    goal: Literal['lose', 'maintain', 'gain', 'recomp']
    pace: Literal['gentle', 'standard']
    diet_type: Literal['omnivore', 'pescatarian', 'vegetarian', 'vegan']
    meals_per_day: Annotated[int, Field(ge=3, le=5)]
    allergens: list[Literal['gluten', 'lactose', 'tree_nuts', 'egg', 'fish', 'shellfish', 'soy', 'peanuts']]
    excluded_food_ids: list[FoodId]
    disliked_food_ids: list[FoodId]
    pregnant: bool
    breastfeeding: bool
    seed: Annotated[int | None, Field(ge=0, le=9007199254740991)]


class NutritionSettingsFields(BaseModel):
    diet_enabled: bool
    goal: Literal['lose', 'maintain', 'gain', 'recomp']
    pace: Literal['gentle', 'standard']
    diet_type: Literal['omnivore', 'pescatarian', 'vegetarian', 'vegan']
    meals_per_day: Annotated[int, Field(ge=3, le=5)]
    allergens: list[Literal['gluten', 'lactose', 'tree_nuts', 'egg', 'fish', 'shellfish', 'soy', 'peanuts']]
    excluded_food_ids: Annotated[list[FoodId], Field(max_length=200)]
    disliked_food_ids: Annotated[list[FoodId], Field(max_length=200)]
    pregnant: Annotated[bool, Field(description='Dato sensible; bloquea la generación de planes.')]
    breastfeeding: Annotated[bool, Field(description='Dato sensible; bloquea la generación de planes.')]


class NutritionSettingsUpdate(NutritionSettingsFields):
    model_config = ConfigDict(
        extra='forbid',
    )


class NutritionSettings(NutritionSettingsFields):
    feature_available: Annotated[bool, Field(description='`DIET_FEATURE_ENABLED` global.')]
    current_target: NutritionTargetRecord | None


class Nutrition(BaseModel):
    settings: NutritionSettingsUpdate | None
    targets: list[NutritionTargetRecord]
    plans: list[MealPlanResource]


class UserExport(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    format: Literal['forja-export']
    schema_version: Literal[1]
    exported_at: AwareDatetime
    app_version: str
    user: User
    profile: Profile
    parq_answers: ParqAnswers | None = None
    body_metrics: list[BodyMetric]
    favorites: list[ExerciseIdValue]
    programs: list[ProgramDetail]
    sessions: list[WorkoutSession]
    personal_records: list[PersonalRecord]
    nutrition: Nutrition
