import { registerBundle } from "../shared/i18nB";

registerBundle(
  "profileB",
  {
    settings: "Ajustes",
    displayName: "Nombre",
    units: "Unidades",
    units_metric: "Métricas (kg, cm)",
    units_imperial: "Imperiales (lb, in)",
    language: "Idioma",
    lang_es: "Español",
    lang_en: "English",
    theme: "Tema",
    theme_dark: "Oscuro",
    theme_light: "Claro",
    theme_system: "Según el sistema",
    sounds: "Sonidos",
    vibration: "Vibración",
    dietEnabled: "Activar el módulo de nutrición",
    defaultRest: "Descanso por defecto (segundos)",
    save: "Guardar ajustes",
    saved: "Ajustes guardados.",
    saveError: "No se han podido guardar los ajustes.",
    data: "Tus datos",
    export: "Exportar mis datos",
    exportError: "No se ha podido exportar.",
    import: "Importar datos",
    importFile: "Archivo de exportación de Forja",
    importDone: "Importado: {{sessions}} sesiones, {{programs}} programas, {{sets}} series.",
    importInvalid: "El archivo no es una exportación válida de Forja.",
    importError: "No se ha podido importar.",
    delete: "Eliminar mi cuenta",
    deleteWarning: "Se borrarán tu cuenta y todos tus datos de forma permanente. Esta acción no se puede deshacer.",
    deletePassword: "Contraseña para confirmar",
    deleteConfirm: "Eliminar definitivamente",
    deleteCancel: "Cancelar",
    deleteError: "No se ha podido eliminar la cuenta. Revisa la contraseña.",
    sessions: "Sesiones activas",
    thisDevice: "Este dispositivo",
    lastSeen: "Última actividad: {{date}}",
    revoke: "Cerrar sesión de {{agent}}",
    unknownAgent: "dispositivo desconocido",
    offline: "Uso sin conexión",
    downloadLibrary: "Descargar biblioteca para uso offline",
    downloading: "Descargando…",
    downloadDone: "Listo: {{count}} medios guardados para uso sin conexión.",
    downloadNone: "No hay un programa activo del que descargar medios.",
    downloadError: "No se ha podido descargar la biblioteca.",
    downloadUnsupported: "Este navegador no permite el uso sin conexión.",
    links: "Más secciones",
    nutrition: "Nutrición",
    admin: "Administración",
  },
  {
    settings: "Settings",
    displayName: "Name",
    units: "Units",
    units_metric: "Metric (kg, cm)",
    units_imperial: "Imperial (lb, in)",
    language: "Language",
    lang_es: "Español",
    lang_en: "English",
    theme: "Theme",
    theme_dark: "Dark",
    theme_light: "Light",
    theme_system: "Follow the system",
    sounds: "Sounds",
    vibration: "Vibration",
    dietEnabled: "Enable nutrition module",
    defaultRest: "Default rest (seconds)",
    save: "Save settings",
    saved: "Settings saved.",
    saveError: "The settings could not be saved.",
    data: "Your data",
    export: "Export my data",
    exportError: "The export failed.",
    import: "Import data",
    importFile: "Forja export file",
    importDone: "Imported: {{sessions}} sessions, {{programs}} programs, {{sets}} sets.",
    importInvalid: "The file is not a valid Forja export.",
    importError: "The import failed.",
    delete: "Delete my account",
    deleteWarning: "Your account and all your data will be permanently deleted. This cannot be undone.",
    deletePassword: "Password to confirm",
    deleteConfirm: "Delete permanently",
    deleteCancel: "Cancel",
    deleteError: "The account could not be deleted. Check the password.",
    sessions: "Active sessions",
    thisDevice: "This device",
    lastSeen: "Last activity: {{date}}",
    revoke: "Sign out {{agent}}",
    unknownAgent: "unknown device",
    offline: "Offline use",
    downloadLibrary: "Download library for offline use",
    downloading: "Downloading…",
    downloadDone: "Done: {{count}} media files saved for offline use.",
    downloadNone: "There is no active program to download media for.",
    downloadError: "The library could not be downloaded.",
    downloadUnsupported: "This browser does not support offline use.",
    links: "More sections",
    nutrition: "Nutrition",
    admin: "Administration",
  },
);
