import { registerBundle } from "../shared/i18nB";

registerBundle(
  "progressB",
  {
    heatmap: "Actividad",
    heatmapHelp: "Cada casilla es un día; cuanto más intensa, más volumen.",
    heatmapCell: "{{date}}: {{sessions}} sesiones, {{volume}} kg",
    heatmapLegendLess: "Menos",
    heatmapLegendMore: "Más",
    volume: "Volumen semanal por grupo muscular",
    week: "Semana",
    effectiveSets: "Series efectivas",
    noVolume: "Aún no hay volumen registrado.",
    e1rmTitle: "e1RM por ejercicio",
    e1rm: "1RM estimado",
    chooseExercise: "Ejercicio",
    noRecordsExercise: "Registra sesiones para ver la evolución de un ejercicio.",
    records: "Récords personales",
    noRecords: "Todavía no hay récords.",
    recordLine: "{{value}} kg",
    recordDetail: "{{weight}} kg × {{reps}}",
    bodyWeight: "Peso corporal",
    weight: "Peso",
    average7d: "Media de 7 días",
    noBodyWeight: "Registra tu peso en «Hoy» para ver la tendencia.",
    showData: "Ver datos en tabla",
    date: "Fecha",
    chartLoading: "Cargando gráfica…",
    group_chest: "Pecho",
    group_back: "Espalda",
    group_shoulders: "Hombros",
    group_arms: "Brazos",
    group_quads: "Cuádriceps",
    group_hamstrings: "Isquiosurales",
    group_glutes: "Glúteos",
    group_calves: "Gemelos",
    group_core: "Core",
    kind_e1rm: "1RM estimado",
    kind_heaviest_set: "Serie más pesada",
    kind_volume: "Volumen",
  },
  {
    heatmap: "Activity",
    heatmapHelp: "Each square is a day; the darker, the more volume.",
    heatmapCell: "{{date}}: {{sessions}} sessions, {{volume}} kg",
    heatmapLegendLess: "Less",
    heatmapLegendMore: "More",
    volume: "Weekly volume per muscle group",
    week: "Week",
    effectiveSets: "Effective sets",
    noVolume: "No volume recorded yet.",
    e1rmTitle: "e1RM per exercise",
    e1rm: "Estimated 1RM",
    chooseExercise: "Exercise",
    noRecordsExercise: "Log sessions to see an exercise's progress.",
    records: "Personal records",
    noRecords: "No records yet.",
    recordLine: "{{value}} kg",
    recordDetail: "{{weight}} kg × {{reps}}",
    bodyWeight: "Body weight",
    weight: "Weight",
    average7d: "7-day average",
    noBodyWeight: "Log your weight in “Today” to see the trend.",
    showData: "Show data as a table",
    date: "Date",
    chartLoading: "Loading chart…",
    group_chest: "Chest",
    group_back: "Back",
    group_shoulders: "Shoulders",
    group_arms: "Arms",
    group_quads: "Quads",
    group_hamstrings: "Hamstrings",
    group_glutes: "Glutes",
    group_calves: "Calves",
    group_core: "Core",
    kind_e1rm: "Estimated 1RM",
    kind_heaviest_set: "Heaviest set",
    kind_volume: "Volume",
  },
);
